# Ariel Configuration File

# GCP Project ID
GCP_PROJECT_ID: "enter project id here"

# GCP Project Location
GCP_PROJECT_LOCATION: "enter project location here"

#GCS Bucket name
GCS_BUCKET_NAME: "enter bucket name here"

# Gemini Model for transcription
GEMINI_MODEL: "gemini-2.5-flash"

# Default audio format
AUDIO_FORMAT: "mp3"

# Default video format
VIDEO_FORMAT: "mp4"

# Gemini API Key
GEMINI_API_KEY: "your gemini api key here"
