# Ariel Configuration File

# GCP Project ID
GCP_PROJECT_ID: "enter project id here"

# GCP Project Location
GCP_PROJECT_LOCATION: "enter project location here"

#GCS Bucket name
GCS_BUCKET_NAME: "enter bucket name here"

#GCS BUCKET USED FOR TEMP FILES
TEMP_BUCKET_NAME: "enter bucket name here"

# Gemini Model for transcription
GEMINI_PRO_MODEL: "gemini-2.5-pro"
GEMINI_FLASH_MODEL: "gemini-2.5-flash"

# Gemini Model for TTS
GEMINI_TTS_FLASH_MODEL: "gemini-2.5-flash-preview-tts"
GEMINI_TTS_PRO_MODEL: "gemini-2.5-pro-preview-tts"

# Default audio format
AUDIO_FORMAT: "mp3"

# Default video format
VIDEO_FORMAT: "mp4"
